#!/usr/bin/env python3
"""
DNS Bot v2 - Project Initialization Script
Creates all necessary configuration files and directories
"""

import os
import sys
import secrets
from pathlib import Path
from typing import Dict, Tuple

# ANSI color codes
class Colors:
    GREEN = '\033[92m'
    RED = '\033[91m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    RESET = '\033[0m'
    BOLD = '\033[1m'

def print_header(text: str):
    """Print a formatted header"""
    print(f"\n{Colors.BOLD}{Colors.BLUE}{'='*60}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}{text:^60}{Colors.RESET}")
    print(f"{Colors.BOLD}{Colors.BLUE}{'='*60}{Colors.RESET}\n")

def print_success(text: str):
    """Print a success message"""
    print(f"{Colors.GREEN}✓{Colors.RESET} {text}")

def print_error(text: str):
    """Print an error message"""
    print(f"{Colors.RED}✗{Colors.RESET} {text}")

def print_warning(text: str):
    """Print a warning message"""
    print(f"{Colors.YELLOW}!{Colors.RESET} {text}")

def print_info(text: str):
    """Print an info message"""
    print(f"{Colors.BLUE}ℹ{Colors.RESET} {text}")

def generate_secret_key(length: int = 32) -> str:
    """Generate a random secret key"""
    return secrets.token_urlsafe(length)

def create_file_if_not_exists(filepath: str, content: str, overwrite: bool = False) -> bool:
    """Create a file with content if it doesn't exist"""
    path = Path(filepath)
    
    if path.exists() and not overwrite:
        print_warning(f"File already exists: {filepath}")
        return False
    
    path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print_success(f"Created: {filepath}")
    return True

def create_backend_env() -> str:
    """Create backend .env file content"""
    secret_key = generate_secret_key()
    
    env_content = f"""# Backend Configuration
# Generated by init-project.py

# Security
SECRET_KEY={secret_key}

# API Keys (Required for production)
GROQ_API_KEY=your_groq_api_key_here
OPENAI_API_KEY=your_openai_api_key_here
GEMINI_API_KEY=your_gemini_api_key_here

# Database
# Local SQLite (Development)
DATABASE_URL=sqlite+aiosqlite:///./app.db

# PostgreSQL (Production)
# DATABASE_URL=postgresql+asyncpg://user:password@localhost:5432/dns_bot

# Redis (Optional)
REDIS_URL=redis://localhost:6379/0

# Server
HOST=0.0.0.0
PORT=8000

# Environment
ENVIRONMENT=development
DEBUG=True

# CORS (For production, specify actual frontend URL)
CORS_ORIGINS=["http://localhost:5173","http://localhost:3000"]

# WebSocket
WEBSOCKET_HEARTBEAT_INTERVAL=30

# AI Model Defaults
DEFAULT_AI_PROVIDER=groq
DEFAULT_MODEL=mixtral-8x7b-32768

# Code Execution
CODE_RUNNER_TIMEOUT=30
CODE_RUNNER_MEMORY_LIMIT=512

# Logging
LOG_LEVEL=INFO
"""
    return env_content

def create_frontend_env() -> str:
    """Create frontend .env.local file content"""
    env_content = """# Frontend Configuration
# Generated by init-project.py

# API Configuration
VITE_API_URL=http://localhost:8000

# WebSocket Configuration
VITE_WS_URL=ws://localhost:8000/ws

# Environment
VITE_ENV=development

# Feature Flags
VITE_ENABLE_LOGGING=true
VITE_ENABLE_DEBUG_PANEL=true

# API Keys (if needed on frontend)
VITE_API_KEY=your_api_key_here
"""
    return env_content

def create_gitignore() -> str:
    """Create .gitignore file content"""
    gitignore_content = """# Environment Variables
.env
.env.local
.env.*.local
*.env

# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
build/
develop-eggs/
dist/
downloads/
eggs/
.eggs/
lib/
lib64/
parts/
sdist/
var/
wheels/
*.egg-info/
.installed.cfg
*.egg
MANIFEST
pip-log.txt
pip-delete-this-directory.txt
.tox/
.coverage
.coverage.*
.cache
nosetests.xml
coverage.xml
*.cover
.hypothesis/
.pytest_cache/
.mypy_cache/
.dmypy.json
dmypy.json
venv/
ENV/
env/
.venv
venv.bak/
env.bak/

# Virtual Environment
virtualenv/

# Node and Frontend
node_modules/
npm-debug.log
yarn-debug.log
yarn-error.log
.next/
.nuxt/
dist/
out/
.nuxt
.cache/
.vuepress/dist
.serverless/
.fusebox/
.dynamodb/
.tern-port
.DS_Store
coverage
.nyc_output
.eslintcache
.node_repl_history

# IDEs
.vscode/
.idea/
*.swp
*.swo
*~
.sublime-project
.sublime-workspace
*.pyc
.project
.pydevproject
.settings/
*.sublime-project
*.sublime-workspace

# OS
.DS_Store
Thumbs.db
.env.local.php
.history

# Database
*.db
*.sqlite
*.sqlite3
app.db

# Docker
docker-compose.override.yml

# Logs
logs/
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
lerna-debug.log*

# Production
dist/
build/
out/

# Temporary files
*.tmp
*.bak
*.swp
*~

# IDE specific
.vscode/settings.json
.idea/workspace.xml
.idea/misc.xml
.idea/modules.xml
.idea/*.iml
.idea/modules/

# OS files
.DS_Store
Thumbs.db
.env.bak
"""
    return gitignore_content

def create_docker_env() -> str:
    """Create .env.docker file for Docker deployment"""
    env_content = """# Docker Environment Configuration
# Used by docker-compose

# Backend Configuration
BACKEND_PORT=8000
BACKEND_HOST=0.0.0.0

# Frontend Configuration
FRONTEND_PORT=5173

# Database
DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/dns_bot
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=dns_bot

# Redis
REDIS_URL=redis://redis:6379/0

# API Keys (Set these in production)
SECRET_KEY=your-secret-key-here-change-in-production
GROQ_API_KEY=your_groq_api_key_here
OPENAI_API_KEY=your_openai_api_key_here
GEMINI_API_KEY=your_gemini_api_key_here

# Environment
ENVIRONMENT=production
DEBUG=False

# CORS for Docker
CORS_ORIGINS=["http://localhost:5173","http://frontend:5173"]
"""
    return env_content

def create_render_env() -> str:
    """Create .env.render file for Render deployment"""
    env_content = """# Render Deployment Environment
# Production settings for Render.com

# Security
SECRET_KEY=your-secure-random-string-here

# API Keys (Required)
GROQ_API_KEY=your_groq_api_key_here
OPENAI_API_KEY=your_openai_api_key_here
GEMINI_API_KEY=your_gemini_api_key_here

# Database (Render PostgreSQL)
DATABASE_URL=postgresql+asyncpg://user:password@your-db-name.onrender.com:5432/your_db_name

# Server
HOST=0.0.0.0
PORT=8000

# Environment
ENVIRONMENT=production
DEBUG=False

# CORS (Set to your actual frontend URL)
CORS_ORIGINS=["https://your-frontend.onrender.com"]

# Redis (Optional Render Redis)
REDIS_URL=redis://your-redis-name:your-password@your-redis-name.onrender.com:6379/0

# Logging
LOG_LEVEL=INFO
"""
    return env_content

def create_readme_env() -> str:
    """Create README.ENV.md with instructions"""
    content = """# Environment Variables Setup Guide

## Overview
This project requires environment variables to run properly. Several `.env.*` templates are provided for different environments.

## Files Generated

### 1. `backend/.env` (Development)
Used for local development with SQLite database.

**Key Variables:**
- `SECRET_KEY`: Random secret for JWT tokens (auto-generated)
- `GROQ_API_KEY`: Groq API key
- `OPENAI_API_KEY`: OpenAI API key
- `GEMINI_API_KEY`: Google Gemini API key
- `DATABASE_URL`: SQLite database URL
- `CORS_ORIGINS`: Frontend URLs allowed to access backend
- `PORT`: Server port (default: 8000)

### 2. `frontend/.env.local` (Development)
Used for local frontend development.

**Key Variables:**
- `VITE_API_URL`: Backend API URL (http://localhost:8000)
- `VITE_WS_URL`: WebSocket backend URL (ws://localhost:8000)

### 3. `.env.docker` (Local Docker)
For running the entire stack locally with Docker Compose.

**Includes:**
- PostgreSQL database configuration
- Redis cache configuration
- All backend API keys

### 4. `.env.render` (Render.com Deployment)
For deploying to Render.com production environment.

**Configuration:**
- Production database URL
- Production environment settings
- Debug mode disabled
- CORS configured for production domain

## API Keys Required

### 1. Groq API
1. Visit: https://console.groq.com
2. Sign up/Login
3. Create API key
4. Copy to `GROQ_API_KEY`

### 2. OpenAI API
1. Visit: https://platform.openai.com/api-keys
2. Sign up/Login
3. Create new API key
4. Copy to `OPENAI_API_KEY`

### 3. Google Gemini API
1. Visit: https://makersuite.google.com/app/apikey
2. Sign up/Login
3. Create new API key
4. Copy to `GEMINI_API_KEY`

## Setup Instructions

### Local Development (SQLite)

```bash
# 1. Copy the generated .env file
cp backend/.env.example backend/.env

# 2. Edit and add your API keys
nano backend/.env

# 3. Run the backend
cd backend
pip install -r requirements.txt
uvicorn app.main:app --reload

# 4. In another terminal, run the frontend
cd frontend
npm install
npm run dev
```

### Local Development (Docker)

```bash
# 1. Use the docker .env file
export $(cat .env.docker | xargs)

# 2. Start all services
docker-compose up -d

# 3. Access services:
# Frontend: http://localhost:5173
# Backend: http://localhost:8000
# API Docs: http://localhost:8000/docs
```

### Production (Render.com)

1. **Create services on Render:**
   - PostgreSQL Database
   - Redis (optional)
   - Web Service for Backend
   - Static Site for Frontend

2. **Configure environment variables:**
   - Set variables from `.env.render` in Render dashboard
   - Use actual API keys and URLs

3. **Deploy:**
   ```bash
   git push origin main
   # Render will automatically deploy
   ```

## Common Configuration Patterns

### Frontend URL in Backend

```env
# Development
CORS_ORIGINS=["http://localhost:5173"]

# Production
CORS_ORIGINS=["https://your-app.onrender.com"]
```

### Database URL Patterns

```env
# SQLite (Development)
DATABASE_URL=sqlite+aiosqlite:///./app.db

# PostgreSQL (Production)
DATABASE_URL=postgresql+asyncpg://user:password@host:5432/dbname
```

### Server Configuration

```env
# Development
HOST=0.0.0.0
PORT=8000
ENVIRONMENT=development
DEBUG=True

# Production
HOST=0.0.0.0
PORT=8000
ENVIRONMENT=production
DEBUG=False
```

## Troubleshooting

### CORS Errors
- Check `CORS_ORIGINS` includes your frontend URL
- For production, use exact URL (e.g., https://yoursite.com)

### API Key Issues
- Verify API key is valid and not expired
- Check if API has usage quota remaining
- Ensure key permissions are configured

### Database Connection Errors
- Verify `DATABASE_URL` is correct
- For PostgreSQL, ensure database exists
- Check credentials and network access

### WebSocket Connection Fails
- Verify `VITE_WS_URL` matches backend URL
- Check CORS settings allow WebSocket connections
- Ensure backend is running with WebSocket middleware

## Security Notes

⚠️ **IMPORTANT:**
- Never commit `.env` files to Git
- .gitignore is configured to exclude them
- Keep API keys secret and rotate regularly
- Use different keys for different environments
- In production, use environment-specific secrets management

## Testing Environment Variables

```bash
# Check if backend can read env variables
python3 << EOF
from dotenv import load_dotenv
import os

load_dotenv()
required_vars = ['SECRET_KEY', 'DATABASE_URL']
for var in required_vars:
    value = os.getenv(var)
    if value:
        print(f"✓ {var} is set")
    else:
        print(f"✗ {var} is missing")
EOF
```

## Next Steps

1. ✓ Generate environment files (done by init-project.py)
2. ☐ Add your API keys to `backend/.env`
3. ☐ Update `CORS_ORIGINS` if needed
4. ☐ Update frontend URLs if not using localhost
5. ☐ Test local development setup
6. ☐ Configure Render deployments
7. ☐ Update production `.env.render` variables

---

For more information, see:
- FastAPI docs: https://fastapi.tiangolo.com
- Vite docs: https://vitejs.dev
- Render docs: https://render.com/docs
- Docker Compose docs: https://docs.docker.com/compose
"""
    return content

def create_structure_verification() -> Tuple[bool, list]:
    """Verify required project structure"""
    required_files = [
        "backend/main.py",
        "backend/requirements.txt",
        "backend/app/main.py",
        "frontend/package.json",
        "docker-compose.yml",
        "DEPLOYMENT.md",
    ]
    
    missing_files = []
    
    for file in required_files:
        if not Path(file).exists():
            missing_files.append(file)
    
    return len(missing_files) == 0, missing_files

def main():
    """Main initialization function"""
    print_header("DNS Bot v2 - Project Initialization")
    
    # Verify project structure
    print_info("Verifying project structure...")
    structure_ok, missing_files = create_structure_verification()
    
    if missing_files:
        print_warning("Some files are missing:")
        for file in missing_files:
            print_error(f"  - {file}")
    else:
        print_success("Project structure verified")
    
    print("\n")
    
    # Create backend .env
    print_info("Creating backend configuration...")
    backend_env = create_backend_env()
    create_file_if_not_exists("backend/.env", backend_env, overwrite=False)
    
    # Create frontend .env.local
    print_info("Creating frontend configuration...")
    frontend_env = create_frontend_env()
    create_file_if_not_exists("frontend/.env.local", frontend_env, overwrite=False)
    
    # Create .gitignore
    print_info("Creating .gitignore...")
    gitignore = create_gitignore()
    create_file_if_not_exists(".gitignore", gitignore, overwrite=False)
    
    # Create Docker env
    print_info("Creating Docker configuration...")
    docker_env = create_docker_env()
    create_file_if_not_exists(".env.docker", docker_env, overwrite=False)
    
    # Create Render env
    print_info("Creating Render deployment configuration...")
    render_env = create_render_env()
    create_file_if_not_exists(".env.render", render_env, overwrite=False)
    
    # Create README for env variables
    print_info("Creating environment variables documentation...")
    readme_env = create_readme_env()
    create_file_if_not_exists("README.ENV.md", readme_env, overwrite=False)
    
    # Summary
    print_header("Initialization Complete")
    
    print(f"{Colors.BOLD}Files Created:{Colors.RESET}")
    print_success("backend/.env - Backend development configuration")
    print_success("frontend/.env.local - Frontend development configuration")
    print_success(".env.docker - Docker Compose configuration")
    print_success(".env.render - Render.com production configuration")
    print_success(".gitignore - Git ignore rules")
    print_success("README.ENV.md - Environment variables documentation")
    
    print(f"\n{Colors.BOLD}Next Steps:{Colors.RESET}")
    print_info("1. Edit backend/.env and add your API keys:")
    print(f"   - GROQ_API_KEY")
    print(f"   - OPENAI_API_KEY")
    print(f"   - GEMINI_API_KEY")
    
    print_info("2. Edit frontend/.env.local if needed")
    
    print_info("3. Start local development:")
    if sys.platform == "win32":
        print(f"   - Run: setup.bat")
    else:
        print(f"   - Run: ./setup.sh")
    
    print_info("4. Read README.ENV.md for detailed configuration guide")
    
    print(f"\n{Colors.BOLD}API Key Setup:{Colors.RESET}")
    print_info("Groq API:")
    print(f"   Visit: https://console.groq.com/keys")
    
    print_info("OpenAI API:")
    print(f"   Visit: https://platform.openai.com/api-keys")
    
    print_info("Google Gemini API:")
    print(f"   Visit: https://makersuite.google.com/app/apikey")
    
    print(f"\n{Colors.GREEN}{Colors.BOLD}✓ Initialization successful!{Colors.RESET}\n")

if __name__ == "__main__":
    main()
